version: "3.8"

services:
  streakbot:
    build: .
    container_name: discord_streak_bot
    restart: unless-stopped
    volumes:
      # Mount secrets directory into the container. Replace the host path with the
      # absolute or relative location of your `secrets` folder on the host.
      - ./secrets:/app/secrets:ro
    environment:
      # Optional: set a timezone inside the container. Adjust as needed.
      - TZ=UTC
      # Provide your Discord bot token here or use Fly.io secrets. When
      # deploying to Fly.io, set DISCORD_TOKEN via `fly secrets set DISCORD_TOKEN=...`.
      # Uncomment and replace with your token if running locally without the secrets file.
      # - DISCORD_TOKEN=your-token-here
      # Bucketeer (S3) credentials can also be supplied via environment variables
      # if you wish to use S3 for persistence when running locally.
